// Generated by CoffeeScript 1.4.0
(function() {
  var $, App, Key, Keys, Panel, Spine, Storage, jquery,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  jquery = require('jquery');

  Spine = require('spine');

  $ = Spine.$;

  global.gui = require('nw.gui');

  global.document = document;

  require('./app/utils/updateAttr');

  Storage = require('./app/utils/storage');

  Panel = require('./app/controllers/panel');

  Keys = require('./app/controllers/keys');

  Key = require('./app/models/key');

  App = (function(_super) {
    var validKeys;

    __extends(App, _super);

    validKeys = [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 186, 187, 188, 189, 190, 191, 219, 220, 221, 222];

    App.prototype.events = {
      'keydown': 'keydown'
    };

    function App() {
      this.keydown = __bind(this.keydown, this);

      var _this = this;
      App.__super__.constructor.apply(this, arguments);
      this.panel = new Panel({
        el: $('header.page')
      });
      this.keys = new Keys({
        el: $('section.page')
      });
      Key.fetch();
      this.key_listening = true;
      Key.bind('focus-input', function() {
        return _this.key_listening = false;
      });
      Key.bind('blur-input', function() {
        return _this.key_listening = true;
      });
    }

    App.prototype.keydown = function(event) {
      if (!this.key_listening) {
        return;
      }
      if (event.keyCode === 27) {
        return this.keys.hideSearch();
      } else if (validKeys.indexOf(event.keyCode) > -1) {
        return this.keys.showSearch();
      }
    };

    return App;

  })(Spine.Controller);

  jQuery(function() {
    return new App({
      el: $('body')
    });
  });

}).call(this);
