// Generated by CoffeeScript 1.4.0
(function() {
  var $, App, Keys, Panel, Spine, jquery,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  jquery = require("jquery");

  Spine = require('./app/libs/spine');

  $ = Spine.$;

  global.gui = require("nw.gui");

  global.document = document;

  Panel = require('./app/controllers/panel');

  Keys = require('./app/controllers/keys');

  App = (function(_super) {

    __extends(App, _super);

    function App() {
      App.__super__.constructor.apply(this, arguments);
      new Panel({
        el: $('header.page')
      });
      new Keys({
        el: $('ul.keys')
      });
    }

    return App;

  })(Spine.Controller);

  jQuery(function() {
    return new App({
      el: $("body")
    });
  });

}).call(this);
