// Generated by CoffeeScript 1.4.0
(function() {
  var Spine,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Spine = require('spine');

  global.Key = (function(_super) {

    __extends(Key, _super);

    function Key() {
      this.toggleEdit = __bind(this.toggleEdit, this);

      this.toggleOpen = __bind(this.toggleOpen, this);

      this.select = __bind(this.select, this);
      return Key.__super__.constructor.apply(this, arguments);
    }

    Key.configure('Key', 'title', 'url', 'username', 'password', 'icon', 'created_on', 'open', 'edited');

    Key.extend(Key.Local);

    Key.filter = function(query) {
      var keys;
      keys = [];
      query = query.toLowerCase();
      Key.each(function(key) {
        if (key.title.toLowerCase().indexOf(query) > -1) {
          return keys.push(key.id);
        }
      });
      return keys;
    };

    Key.deselectAll = function() {
      var key, selected, _i, _len, _results;
      selected = Key.select(function(key) {
        var _ref;
        return (_ref = key.selected) != null ? _ref : false;
      });
      _results = [];
      for (_i = 0, _len = selected.length; _i < _len; _i++) {
        key = selected[_i];
        key.selected = false;
        _results.push(key.trigger('deselect'));
      }
      return _results;
    };

    Key.closeAll = function() {
      var key, open, _i, _len, _results;
      open = Key.select(function(key) {
        var _ref;
        return (_ref = key.open) != null ? _ref : false;
      });
      _results = [];
      for (_i = 0, _len = open.length; _i < _len; _i++) {
        key = open[_i];
        if (key.edited) {
          key.toggleEdit(false);
        }
        key.updateAttribute('open', false);
        _results.push(key.trigger('close'));
      }
      return _results;
    };

    Key.prototype.select = function() {
      Key.deselectAll();
      this.selected = true;
      return this.trigger('select');
    };

    Key.prototype.toggleOpen = function(value) {
      var open;
      open = value != null ? value : !this.open;
      Key.closeAll();
      if (open === false) {
        return;
      }
      this.updateAttribute('open', true);
      return this.trigger('open');
    };

    Key.prototype.toggleEdit = function(value) {
      this.updateAttribute('edited', value ? value : !this.edited);
      return this.trigger(this.edited ? 'open-edit' : 'close-edit');
    };

    return Key;

  }).call(this, Spine.Model);

  module.exports = Key;

}).call(this);
